[package]
name = "sasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "sasm_lib"

[[bin]]
name = "sasm"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
common = { path = "../common" }
